#!/bin/sh
# shellcheck disable=SC2034

pkgname=yaft-rm2-stuff
pkgver=0.1.3
pkgrel=1
pkgdesc="Yaft terminal emulator built from the rM2-stuff fork"
url="https://github.com/timower/rM2-stuff"
license=('GPL-3.0-only')
arch=('armv7-3.2' 'armv7-3.3' 'armv7-3.5' 'armv7-3.8' 'armv7-3.20' 'armv7-3.22')
depends=('rm2fb-client')
makedepends=('cmake' 'ninja' 'pkgconf' 'git')
provides=('yaft')
conflicts=('yaft')
source=("git+https://github.com/timower/rM2-stuff.git#commit=77fd07986c962f7603bdf490adc41dff1aaea613")
sha256sums=('SKIP')

build() {
  cd "$srcdir/rM2-stuff"

  cmake --preset release-toltec
  cmake --build build/release-toltec --target yaft yaft_reader
}

package() {
  cd "$srcdir/rM2-stuff"

  DESTDIR="$pkgdir" cmake --install build/release-toltec --component yaft
}
